### PR TITLE
updated flutter 3.7

### PR DESCRIPTION
**Pull request by LOCKEDFILE**
updated flutter 3.7

### CODE REVIEW

**Comment by jonbhanson** [comment]
I tried this manually on my Flutter 3.7 upgrade and it fixed the problem.

**Comment by mumenma** [comment]
Please

**Review by hoveizkabuli — APPROVED** [review]

**Comment by hoveizkabuli** [comment]
these changes need to merge asap  please

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_text/commit/5714918f6b05e670bf26c1437b0c139a4708015c

**Pull request closed without merging**
